name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  x86_64-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    name: x86-64 Windows MSVC
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install Dependencies
        run: |
          function msys() { C:\msys64\usr\bin\bash.exe @('-lc') + @Args }; msys ' '; msys 'pacman --noconfirm -Syuu'; msys 'pacman --noconfirm -Syuu'; msys 'pacman --noconfirm -S --needed base-devel mingw-w64-x86_64-lldb'; msys 'pacman --noconfirm -Scc'
      - name: Restore Libs Cache
        id: restore-libs
        uses: actions/cache/restore@v4
        with:
          path: build/libs
          key: libs-windows-latest-${{ hashFiles('make.ps1', 'CMakeLists.txt', 'lib/CMakeLists.txt', 'lib/llvm/patches/*') }}
      - name: Build Libs
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: .\make.ps1 -Command libs
      - name: Save Libs Cache
        if: steps.restore-libs.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: build/libs
          key: libs-windows-2025-${{ hashFiles('make.ps1', 'CMakeLists.txt', 'lib/CMakeLists.txt', 'lib/llvm/patches/*') }}
      - name: Build Debug Runtime
        run: |
          .\make.ps1 -Command configure -Config Debug
          .\make.ps1 -Command build -Config Debug
      - name: Test with Debug Runtime
        run: .\make.ps1 -Command test -Config Debug -Uselldb yes
      - name: Build Release Runtime
        run: |
          .\make.ps1 -Command configure -Config Release
          .\make.ps1 -Command build -Config Release
      - name: Test with Release Runtime
        run: .\make.ps1 -Command test -Config Release -Uselldb yes
      - name: Build examples
        run: .\make.ps1 -Command build-examples
  
  arm64-macos:
    runs-on: macos-latest

    name: arm64 Apple Darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Restore Libs Cache
        id: restore-libs
        uses: actions/cache/restore@v4
        with:
          path: build/libs
          key: libs-arm64-macos-latest-${{ hashFiles('Makefile', 'CMakeLists.txt', 'lib/CMakeLists.txt', 'lib/llvm/patches/*') }}
      - name: Build Libs
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: make libs build_flags=-j8
      - name: Save Libs Cache
        if: steps.restore-libs.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: build/libs
          key: libs-arm64-macos-latest-${{ hashFiles('Makefile', 'CMakeLists.txt', 'lib/CMakeLists.txt', 'lib/llvm/patches/*') }}
      - name: Build Debug Runtime
        run: |
          make configure arch=armv8  config=debug
          make build config=debug
      - name: Test with Debug Runtime
        run: make test-ci config=debug
      - name: Build Release Runtime
        run: |
          make configure arch=armv8  config=release
          make build config=release
      - name: Test with Release Runtime
        run: make test-ci config=release

  x86_64-linux:
    runs-on: ubuntu-latest

    name: x86-64 Ubuntu Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install lldb
        run: sudo apt install -y lldb
      - name: Restore Libs Cache
        id: restore-libs
        uses: actions/cache/restore@v4
        with:
          path: build/libs
          key: libs-x86_64-ubuntu-latest-${{ hashFiles('Makefile', 'CMakeLists.txt', 'lib/CMakeLists.txt', 'lib/llvm/patches/*') }}
      - name: Build Libs
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: make libs build_flags=-j8
      - name: Save Libs Cache
        if: steps.restore-libs.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: build/libs
          key: libs-${{ matrix.image }}-${{ hashFiles('Makefile', 'CMakeLists.txt', 'lib/CMakeLists.txt', 'lib/llvm/patches/*') }}
      - name: Build Debug Runtime
        run: |
          make configure arch=x86-64 config=debug
          make build config=debug
      - name: Test with Debug Runtime
        run: make test-ci config=debug usedebugger=lldb
      - name: Build Release Runtime
        run: |
          make configure arch=x86-64 config=release
          make build config=release
      - name: Test with Release Runtime
        run: make test-ci config=release usedebugger=lldb
  
